apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: my-deployment
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-deployment
          image: nginx
          imagePullPolicy: IfNotPresent
        - name: my-side-container
          image: side-container
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: my-deployment
