apiVersion: v1
kind: Pod
metadata:
  name: sleeper-pod
  labels:
    app: sleeper-pod
spec:
  containers:
    - name: sleeper-pod
      image: ubuntu-sleeper
      imagePullPolicy: IfNotPresent
      #Override the CMD instruction in the Dockerfile
      args:
        - "10"
      #Override the ENTRYPOINT in the Dockerfile
      command:
        - sleep2.0
  restartPolicy: Always
