apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
    - name: my-pod
      image: nginx
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: my-secret
  restartPolicy: Always
