apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeSelector:
    size: large