apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
    function: backend
spec:
  containers:
    - name: my-pod
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
