apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
    - name: my-pod
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  tolerations:
    - key: app
      operator: Equal
      value: frontend
      effect: NoSchedule