apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
    - name: my-pod
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  #Same as nodeSelector
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - large
                  - medium
          - matchExpressions:
              - key: size
                operator: NotIn
                values:
                  - small